import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import {dark} from "@clerk/themes";
import Sidebar from "@/components/sidebar";
import { auth } from "@clerk/nextjs/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  const { sessionClaims: user } = auth();

  const isAdmin = user?.metadata.role === "admin"
  return (
  <ClerkProvider appearance={{ baseTheme: dark }}>
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
      >
        <div className="flex flex-row">
        <Sidebar isAdmin={isAdmin}/>
            {children}
        </div>
    </ThemeProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
