import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import {dark} from "@clerk/themes";
import Sidebar from "@/components/sidebar";
import { auth } from "@clerk/nextjs/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  let hidden = "";
  const { sessionClaims: user } = auth();
  if (!user){
    hidden = "collapse"
  }
  const isAdmin = user?.metadata.role === "admin"

  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              <Sidebar isAdmin={isAdmin} hidden={hidden} />
              <main className="flex-1">
                {children}
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
